#!/usr/bin/env bash

count=0
disconnected=""
disconnected1="Nah!"
wireless_connected=" wireless"
ethernet_connected=" Ethernet"
echeck="e*"

SSID_NAME=$(iwgetid -r)
ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
        if [[ "$ID" == $echeck ]]; then
            echo "$ethernet_connected" ; sleep 5
        else
            echo "$wireless_connected" "${SSID_NAME}"; sleep 5
        fi
    else
        echo "$disconnected" "$disconnected1"; sleep 0.5
    fi
done

~/.config/polybar/scripts/check-network
